name: CI

on:
  - push
  - pull_request


concurrency:
  group: ${{ github.ref }}-${{ github.workflow }}
  cancel-in-progress: true


jobs:
  build-and-test:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-24.04, ubuntu-24.04-arm, macos-13, macos-14]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - uses: conda-incubator/setup-miniconda@v3
        with:
          python-version: ${{ matrix.python-version }}
          miniforge-variant: Miniforge3
          miniforge-version: latest
          auto-update-conda: true
          channels: conda-forge,defaults

      - name: Install dependencies
        run: conda install c-compiler cmake

      - name: Build
        shell: bash
        run: |
          cmake -S . -B _build -DCMAKE_INSTALL_PREFIX=_inst
          cmake --build _build --target all
          cmake --build _build --target install

      - name: Run Tests
        shell: bash
        run: |
          _inst/bin/cem --help
          _inst/bin/cem --version
          _inst/bin/cem

